FROM python:3.9

WORKDIR /app/src

COPY ./requirements.txt /app/requirements.txt

RUN python -m venv /root/venv && \
    . /root/venv/bin/activate && \
    python -m ensurepip && \
    python -m pip install -r /app/requirements.txt
