version: "2"

services:
  ffmpeg:
    command: /app/bin/snapz.sh
    env_file: ./.env
    image: linuxserver/ffmpeg
    volumes:
      - ./:/app
    working_dir: /app

  imagemagick:
    entrypoint: /app/bin/thumbz.sh
    env_file: ./.env
    image: dpokidov/imagemagick
    volumes:
      - ./:/app
    working_dir: /app

  pagez:
    build:
      context: .
      dockerfile: Dockerfile.pagez
    command: /app/bin/pagez.sh
    env_file: ./.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app