# Generated by Django 4.0.4 on 2022-05-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='thumb',
            old_name='file_name',
            new_name='filename',
        ),
    ]
