# Generated by Django 4.0.4 on 2022-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_video_description_video_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['video__title', 'filename']},
        ),
        migrations.AlterModelOptions(
            name='thumb',
            options={'ordering': ['video__title', 'filename']},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['video'], name='videos_imag_video_i_087f79_idx'),
        ),
        migrations.AddIndex(
            model_name='thumb',
            index=models.Index(fields=['video'], name='videos_thum_video_i_b462a7_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='videos_vide_title_8a2e81_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['filename'], name='videos_vide_filenam_36d82e_idx'),
        ),
    ]
