# Generated by Django 4.0.4 on 2022-05-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('videos', '0013_alter_image_options_alter_thumb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag', unique=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='videos.video', unique=True)),
            ],
            options={
                'ordering': ['video', 'tag'],
            },
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['tag'], name='videos_vide_tag_id_0c61e6_idx'),
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['video'], name='videos_vide_video_i_d09316_idx'),
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['tag', 'video'], name='videos_vide_tag_id_b43439_idx'),
        ),
    ]
