# Generated by Django 4.0.4 on 2022-05-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('videos', '0014_videotag_videotag_videos_vide_tag_id_0c61e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='videos.video'),
        ),
    ]
