# Generated by Django 4.0.4 on 2025-01-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_slug_alter_tag_text'),
        ('videos', '0015_alter_videotag_tag_alter_videotag_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='thumb',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='ThumbTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag')),
                ('thumb', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='videos.thumb')),
            ],
            options={
                'ordering': ['thumb', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='videos.image')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag')),
            ],
            options={
                'ordering': ['image', 'tag'],
            },
        ),
        migrations.AddIndex(
            model_name='thumbtag',
            index=models.Index(fields=['tag'], name='videos_thum_tag_id_3f0871_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbtag',
            index=models.Index(fields=['thumb'], name='videos_thum_thumb_i_5bee92_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbtag',
            index=models.Index(fields=['tag', 'thumb'], name='videos_thum_tag_id_31996e_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['tag'], name='videos_imag_tag_id_023f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['image'], name='videos_imag_image_i_1d3ede_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['tag', 'image'], name='videos_imag_tag_id_b0d77e_idx'),
        ),
    ]
