# Generated by Django 4.0.4 on 2022-05-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['text'], name='tags_tag_text_afbcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tags_tag_slug_dcb0c2_idx'),
        ),
    ]
